### ISSUE TITLE
Combination of Blade's block level directives and PHP's alternative foreach syntax make formatter add indent forever

### ISSUE THREAD

**Issue by wb-joona** [shufo/blade-formatter#305] opened 2021-07-07 11:57 UTC
## Expected Behavior

I would expect the formatter to not add indentation on each format.

## Current Behavior

When formatting a document which is wrapped in a block-level directive like `@section('')`, using other block-level Blade directives like `@if` and `@foreach` inside an PHP alternative style foreach block cause the formatter to keep adding indentation on each format.

## Steps to Reproduce
1. Format the following code with blade-formatter 1.11.9:
```
@section('section')
<?php
    foreach ($foos as $foo):
?>
    @if($foo)
        <div><?= $foo ?></div>
    @endif
<?php endforeach; ?>
@endsection
```
2. Observe that the output is the following. Notice the mismatched indentation on `@if` and `@foreach`
```
@section('section')
    <?php foreach ($foos as $foo): ?>
    @if ($foo)
        <div><?= $foo ?></div>
        @endif
    <?php endforeach; ?>
@endsection
```
3. Format the same document again, and observe that the output is:
```
@section('section')
    <?php foreach ($foos as $foo): ?>
    @if ($foo)
        <div><?= $foo ?></div>
            @endif
        <?php endforeach; ?>
@endsection
```

4. Format again:
```
@section('section')
    <?php foreach ($foos as $foo): ?>
    @if ($foo)
        <div><?= $foo ?></div>
                @endif
            <?php endforeach; ?>
@endsection
```
5. And a few more times:
```
@section('section')
    <?php foreach ($foos as $foo): ?>
    @if ($foo)
        <div><?= $foo ?></div>
                                                @endif
                                            <?php endforeach; ?>
@endsection
```

Here's a gif:

![RfVFaE6M6k](https://user-images.githubusercontent.com/85222502/124755113-a20cb500-df33-11eb-801b-39e19557a2e5.gif)

**Comment by shufo** [comment] 2021-07-07 19:03
Hi @wb-joona. Thanks you for creating the issue!
I also saw this behaviour sometimes and it seems short php tag `<?=` causes this behaviour.

So If you write with full qualified php tag `<?php ~ ?>` like below would not happen this behaviour

```blade
@section('section')
    <?php foreach ($foos as $foo): ?>
    @if ($foo)
        <div><?php $foo; ?></div>
    @endif
    <?php endforeach; ?>
@endsection
```

### Reproducing Screencasts

https://user-images.githubusercontent.com/1641039/124814549-1a5d8f80-dfa1-11eb-9872-7fbddb2869b3.mp4

**Comment by shufo** [comment] 2021-07-07 19:14
PHP short open tag is now [deprecated](https://wiki.php.net/rfc/deprecate_php_short_tags) since PHP 8.

```php
root@b932e5e95a6e:/# php -v
PHP 8.0.8 (cli) (built: Jul  1 2021 22:23:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
root@b932e5e95a6e:/# php
<?=
echo 1;

Parse error: syntax error, unexpected token "echo" in Standard input code on line 2
root@b932e5e95a6e:/# php
<?php
echo 1;
1root@b932e5e95a6e:/#
```

So short tag should be migrate to full open tag `<?php ~ ?>` in some point...but I will take look at it for backward compatibility.

**Comment by shufo** [comment] 2021-07-07 19:32
Uh no. It was my misconception.
PHP short tag deprecation proposal was declined because vote didn't reach 2/3 majority.
https://wiki.php.net/rfc/deprecate_php_short_tags_v2
To be precise, it still works, but since many people voted for Deperecation both times, it's better to migrate.

**Comment by lelgenio** [comment] 2021-07-10 03:08
I'm also having this probem with multiline strings inside `@php` blocks.
```blade
@php
$myvar = "lorem
ipsum";
@endphp
```
after formatted a few times, becomes:
```blade
@php
    $myvar = "lorem
                                            ipsum";
@endphp
```

**Comment by shufo** [comment] 2021-07-12 18:09
@wb-joona 
This behaviour is now fixed in https://github.com/shufo/blade-formatter/releases/tag/v1.11.10

https://user-images.githubusercontent.com/1641039/125335475-8ec07600-e387-11eb-820f-cfb9d500cd60.mp4

**Comment by shufo** [comment] 2021-07-12 18:22
@lelgenio 
It seems indentation before `@php` directive causes this behaviour.

![image](https://user-images.githubusercontent.com/1641039/125336738-207cb300-e389-11eb-8318-fe279df5ecf1.png)

It unexpectedly increment indent level on every time you format template. 

Current workaround is to place `@php` directive without indentation

```blade
@php
$myvar = "lorem  
  ipsum";
@endphp
```

or use escape character with double quote

```blade
@php
$myvar = "lorem\n    ipsum";
@endphp
```

**Closed** 2022-03-19 14:05 UTC
Labels: bug
